### ISSUE TITLE
An error found in step 6) codes

### ISSUE THREAD

**Issue by davidhasan** [abhashpanwar/credit-risk-modeling#1]
Hello Abhash,
It is a great job, thank you for sharing the codes. I got an error in step 6) when I run the code of: 

in: lgd_inputs_stage_1_train = lgd_inputs_stage_1_train[features_all]

out: KeyError:"['term_int', 'mths_since_earliest_cr_line', 'mths_since_issue_d'] not in index"

I should say that I used the "loan_data_2007_2014_v2.csv" data instead of "loan_data_2007_2014_preprocessed.csv" because I couldn't find where you created the "loan_data_2007_2014_preprocessed.csv" data set. I appreciate any help in advance.

**Comment by abhashpanwar** [comment]
The dataset loan_data_2007_2014_preprocessed.csv is nothing but data that is preprocessed in step1 and I have downloaded this dataset along with the raw dataset.

**Comment by davidhasan** [comment]
I've solved it. Thank you for the response.
